name: Continuous integration

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    timeout-minutes: 10

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release
